# 2023-02-01

In [1]:
# combination quiz(2)
n = int(input())
cache = [-1] * 1001
cache[1] = 1
cache[2] = 2

for i in range(3, 1001):
    cache[i] = (cache[i-1] + cache[i-2]) % 10007    # 1, 2 연산은 불가하기 때문에 위에서 미리 지정
print(cache[n])

 9


55


In [11]:
# combination quiz(3)
cache = [[0] * 10 for _ in range(101)]      # N x n size가 들어갈 cache테이블을 만들어야 함/ N은 100보다 작은 수, n은 0~9의 수 이므로


for d in range(1, 10):    # 길이가 1이고 마지막 숫자가 1~9인 데이터를 미리 넣어줌
    cache[1][d] = 1
    
for n in range(2, 101):
    for d in range(10):
        if d == 0:                         # 0이 올 때 - cache[n-1][d+1] 만 적용됨
            cache[n][d] = cache[n-1][d+1]
        elif d == 9:                       # 9가 올 때 - cache[n-1][d-1] 만 적용됨
            cache[n][d] = cache[n-1][d-1]
        else:
            cache[n][d] = cache[n-1][d-1] + cache[n-1][d+1]
        cache[n][d] %= 1_000_000_000

N = int(input())
result = 0
for d in range(10):
    result += cache[N][d]
    result %= 1_000_000_000
print(result)

 2


17


# Python Library

## 1. Numpy

In [2]:
import numpy as np

### array 생성하기

In [18]:
array_1D = np.array([1, 2, 3])
print(array_1D)
print(array_1D.shape)

array_2D = np.array([[1, 2, 3],
                   [4, 5, 6]])
print(array_2D)
print(array_2D.shape)

array_3D = np.array([[[1, 2, 3],
                   [4, 5, 6]],
                    [[1, 2, 3],
                   [4, 5, 6]]])
print(array_3D)
print(array_3D.shape)

[1 2 3]
(3,)
[[1 2 3]
 [4 5 6]]
(2, 3)
[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]
(2, 2, 3)


In [22]:
# array_2D = shape (2, 3)
# 5를 가져오려면?
array_2D[1][1]

5

In [25]:
# array_3D = shape(2, 2, 3)
array_3D[0][1]

array([4, 5, 6])

In [6]:
array_3D[0][1, 1]

5

### 기초통계량 활용

In [26]:
array_1D.sum()  # list에선 연산이 불가하지만 numpy array로 만든 후 연산이 가능하다.

6

In [28]:
array_2D.max()

6

In [29]:
array_2D.mean()

3.5

In [30]:
array_2D.min()

1

In [31]:
array_2D.sum()

21

### 모양 변경하기

In [32]:
array = np.arange(15)
print(array)
print(array.shape)   # (15,)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]
(15,)


In [34]:
# 3 x 5 array로 변경
reshape_array = array.reshape(3, 5)
print(reshape_array)
print(reshape_array.shape)
print(reshape_array.size)       # 크기(갯수)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]
(3, 5)
15


In [36]:
array_1D = np.arange(0, 100, 5)
print(array_1D)
print(array_1D.size)
print(array_1D.shape)

[ 0  5 10 15 20 25 30 35 40 45 50 55 60 65 70 75 80 85 90 95]
20
(20,)


In [39]:
# 3차원으로 변경
reshape_array_3D = array_1D.reshape(2, 2, 5)
print(reshape_array_3D)
print(reshape_array_3D.size)
print(reshape_array_3D.shape)
print(reshape_array_3D.ndim)

[[[ 0  5 10 15 20]
  [25 30 35 40 45]]

 [[50 55 60 65 70]
  [75 80 85 90 95]]]
20
(2, 2, 5)
3


### numpy array operation

In [40]:
data = [1, 2, 3]

In [41]:
np.array(data) * 10

array([10, 20, 30])

In [43]:
array1 = np.array([[1, 0],
                  [0, 1]])
array2 = np.array([[1, 2],
                  [3, 4]])
print(array1 + array2)
print(array1 - array2)
print(array1 * array2)
print(array1 / array2)

[[2 2]
 [3 5]]
[[ 0 -2]
 [-3 -3]]
[[1 0]
 [0 4]]
[[1.   0.  ]
 [0.   0.25]]


In [46]:
array1 * array2

array([[1, 0],
       [0, 4]])

In [47]:
# 행렬 곱 연산(내적)
np.dot(array1, array2)

array([[1, 2],
       [3, 4]])

### 다차원 연산

In [51]:
n3 = np.arange(1, 13).reshape(3, 4)      # 1부터 12까지의 원소를 가지는 (3, 4)형태의 행렬 생성
n3

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [52]:
print(n3.std())     # 표준편차
print(n3.var())     # 분산
print(n3.cumsum())  # 누적합
print(n3.cumprod()) # 누적곱

3.452052529534663
11.916666666666666
[ 1  3  6 10 15 21 28 36 45 55 66 78]
[        1         2         6        24       120       720      5040
     40320    362880   3628800  39916800 479001600]


In [55]:
n3.sum(axis = 0)   # 각 column들의 합계를 구함

array([15, 18, 21, 24])

In [56]:
n3.sum(axis = 1)   # 각 row들의 합계를 구함

array([10, 26, 42])

In [58]:
n3.max(axis = 0)      # 각 column들에서의 최대값

array([ 9, 10, 11, 12])

In [59]:
n3.max(axis = 1)  

array([ 4,  8, 12])

In [60]:
n3.cumsum(axis=0)     # column방향으로의 누적합

array([[ 1,  2,  3,  4],
       [ 6,  8, 10, 12],
       [15, 18, 21, 24]])

In [61]:
n3.cumsum(axis=1)     # row방향으로의 누적합

array([[ 1,  3,  6, 10],
       [ 5, 11, 18, 26],
       [ 9, 19, 30, 42]])

### Stack

In [63]:
v1 = np.arange(11, 16)
print(v1)
v2 = v1 + 10            # array방향이므로 각 원소에 10을 더함
v3 = v2 + 10
v4 = v3 + 10
print(v4)

[11 12 13 14 15]
[41 42 43 44 45]


In [68]:
vstack1 = np.vstack((v1, v2))
print(vstack1)
vstack2 = np.vstack((v3, v4))
print(vstack2)
print('*' * 20)
v = np.vstack((v1, v2, v3, v4))
print(v)

[[11 12 13 14 15]
 [21 22 23 24 25]]
[[31 32 33 34 35]
 [41 42 43 44 45]]
********************
[[11 12 13 14 15]
 [21 22 23 24 25]
 [31 32 33 34 35]
 [41 42 43 44 45]]


In [69]:
print(v1.shape)
print(vstack1.shape)
print(v.shape)

(5,)
(2, 5)
(4, 5)


In [73]:
# v에서 23을 선택하려면?
v[1][2]     # v[1, 2]도 가능

23

In [75]:
v[:, 1]

array([12, 22, 32, 42])

In [76]:
v[1:3, 1]

array([22, 32])

In [77]:
v[1, :]

array([21, 22, 23, 24, 25])

### 실습

In [80]:
v = np.array([[11, 12, 13, 14, 15],
              [21, 22, 23, 24, 25],
              [31, 32, 33, 34, 35],
              [41, 42, 43, 44, 45]])

In [82]:
# Q1. [33, 34]

v[2][2:4]

array([33, 34])

In [83]:
# Q2. [14, 24, 34, 44]
v[:, 3]

array([14, 24, 34, 44])

In [92]:
# Q3. [[23, 24],
#      [33, 34]]
print(v[1:3, 2:4])

[[23 24]
 [33 34]]


### 조건연산

In [93]:
# 불린(boolean)추출 - 조건에 충족하면 True, 그렇지 않은 경우 False
arr = np.array([10, 20, 30])
arr > 10

array([False,  True,  True])

In [94]:
arr[arr > 10]      # 조건 데이터를 list형태로 만들어 가져오면 True값만 얻어올 수 있다.

array([20, 30])

In [95]:
arr[(arr > 10) & (arr < 30)]     # 10보다 크고 30보다 작은 수 / & ->두 조건 모두 만족해야 함

array([20])

In [96]:
condition = arr > 10
arr[~condition]              # '~' 위 condition의 역조건

array([10])

In [97]:
# where

arr2 = np.where(arr > 10, 1, 0)     # where(arr > 10, True면 1, False면 0)
arr2

array([0, 1, 1])

In [98]:
arr3 = np.where(arr > 10, arr + 10, arr - 10)    # True, False 자리는 고정 (arr > 10, True면 arr+10, False면 arr-10)
arr3

array([ 0, 30, 40])

## 2. Pandas

In [11]:
import pandas as pd

### Series

In [100]:
pd.date_range('2022-01-01', '2023-01-01', freq = 'M' )       # 날짜 data 생성 - 시작, 끝, 빈도('D', 'W', 'M'..)

DatetimeIndex(['2022-01-31', '2022-02-28', '2022-03-31', '2022-04-30',
               '2022-05-31', '2022-06-30', '2022-07-31', '2022-08-31',
               '2022-09-30', '2022-10-31', '2022-11-30', '2022-12-31'],
              dtype='datetime64[ns]', freq='M')

In [101]:
pd.date_range('2022-01-01', '2023-01-01', freq = 'MS' )    # freq = 'MS' 월의 첫째날

DatetimeIndex(['2022-01-01', '2022-02-01', '2022-03-01', '2022-04-01',
               '2022-05-01', '2022-06-01', '2022-07-01', '2022-08-01',
               '2022-09-01', '2022-10-01', '2022-11-01', '2022-12-01',
               '2023-01-01'],
              dtype='datetime64[ns]', freq='MS')

In [102]:
prices = [1000, 1010, 1020]
dates = pd.date_range('20230101', periods = 3)
dates

DatetimeIndex(['2023-01-01', '2023-01-02', '2023-01-03'], dtype='datetime64[ns]', freq='D')

In [104]:
Series1 = pd.Series(prices, index = dates)   # dates를 index로 하고 prices의 값들을 가지는 Series객체 생성
Series1

2023-01-01    1000
2023-01-02    1010
2023-01-03    1020
Freq: D, dtype: int64

In [107]:
# 값 추가
Series1['2023-01-04'] = 1030
Series1

2023-01-01    1000
2023-01-02    1010
2023-01-03    1020
2023-01-04    1030
Freq: D, dtype: int64

In [108]:
# 값 불러오기 1
Series1[2]

1020

In [109]:
# 값 불러오기 2
Series1['2023-01-02']

1010

In [113]:
Series2 = pd.Series(prices)    # index 지정 없이 Series객체 생성
Series2

0    1000
1    1010
2    1020
dtype: int64

In [112]:
Series2[3] = 1030
Series2

0    1000
1    1010
2    1020
3    1030
dtype: int64

### DataFrame

In [12]:
prices = {
    "A텔레콤" : [48000, 48500, 49000],     # A, B, C -> columns / data의 길이가 같아야 DF생성가능
    "B전자" : [60000, 61000, 62000],
    "C은행" : [54000, 55000, 56000]
}

df1 = pd.DataFrame(prices)
df1

A텔레콤    B전자    C은행
0  48000  60000  54000
1  48500  61000  55000
2  49000  62000  56000

In [14]:
# DataFrame의 index값으로 넣을 날짜 생성
dates = pd.date_range('2023-01-02', periods = 3)
dates

DatetimeIndex(['2023-01-02', '2023-01-03', '2023-01-04'], dtype='datetime64[ns]', freq='D')

In [15]:
df2 = pd.DataFrame(prices, index = dates)          # DataFrame도 역시 index를 지정하여 넣을 수 있다.
df2

A텔레콤    B전자    C은행
2023-01-02  48000  60000  54000
2023-01-03  48500  61000  55000
2023-01-04  49000  62000  56000

### 데이터 선택
 - iloc : 데이터 순서로 데이터를 가져온다.
 - loc : index, column으로 데이터를 가져온다.

In [16]:
df2

A텔레콤    B전자    C은행
2023-01-02  48000  60000  54000
2023-01-03  48500  61000  55000
2023-01-04  49000  62000  56000

In [118]:
df2.iloc[0]    # row

A텔레콤    48000
B전자     60000
C은행     54000
Name: 2023-01-02 00:00:00, dtype: int64

In [119]:
df2.iloc[:, 0]    # column

2023-01-02    48000
2023-01-03    48500
2023-01-04    49000
Freq: D, Name: A텔레콤, dtype: int64

In [121]:
df2.iloc[0, 0]   # row와 column에 해당하는 값 하나만

48000

In [123]:
df2.loc['2023-01-02', 'A텔레콤']        # index명으로

48000

In [124]:
df2.loc['2023-01-02']

A텔레콤    48000
B전자     60000
C은행     54000
Name: 2023-01-02 00:00:00, dtype: int64

In [125]:
df2.loc[:, 'A텔레콤']

2023-01-02    48000
2023-01-03    48500
2023-01-04    49000
Freq: D, Name: A텔레콤, dtype: int64

In [126]:
df2.A텔레콤

2023-01-02    48000
2023-01-03    48500
2023-01-04    49000
Freq: D, Name: A텔레콤, dtype: int64

In [127]:
df2['A텔레콤']['2023-01-03']

48500

In [128]:
df2.loc[:, 'A텔레콤']['2023-01-03']

48500

### 실습

In [17]:
df2['D철강'] = [5000, 5100, 5200]
df2

A텔레콤    B전자    C은행   D철강
2023-01-02  48000  60000  54000  5000
2023-01-03  48500  61000  55000  5100
2023-01-04  49000  62000  56000  5200

1. 2023년 1월 3일 ~ 2023년 1월 4일 까지의 ‘B 전자’, ‘C 은행’ 데이터를 가져와주세요

In [137]:
# iloc
df2.iloc[1:, [1, 2]]    # or df2.iloc[1:, 1:3]

B전자    C은행
2023-01-03  61000  55000
2023-01-04  62000  56000

In [138]:
# loc
df2.loc['2023-01-03':, 'B전자':'C은행']

B전자    C은행
2023-01-03  61000  55000
2023-01-04  62000  56000

2. 데이터 61000원 가져오기(iloc, loc 각각 활용)

In [143]:
df2.iloc[1, 1]

61000

In [144]:
df2.loc['2023-01-03', 'B전자']

61000

## 데이터프레임 확장
 - concat : 그냥 가져다 붙이는 것 (index, columns 같은 경우)
 - merge : 공통된 컬럼이나 인덱스가 있는 경우 결합

In [45]:
dates = pd.date_range('2023-01-02', periods = 3)
s1 = pd.Series([3000, 3100, 3200], index = dates)
s1.name = 'F화학'                                 # column명 지정
s1

2023-01-02    3000
2023-01-03    3100
2023-01-04    3200
Freq: D, Name: F화학, dtype: int64

In [46]:
concat_df2 = pd.concat([df2, s1], axis = 1)             # df와 series or df와 df 끼리 concat가능 (붙일 방향도 지정해야 함), 가로(row) 방향으로
concat_df2

A텔레콤    B전자    C은행   D철강   F화학
2023-01-02  48000  60000  54000  5000  3000
2023-01-03  48500  61000  55000  5100  3100
2023-01-04  49000  62000  56000  5200  3200

In [47]:
concat_df2['F화학_add_500'] = concat_df2['F화학'] + 500    # 한 column의 값들을 연산하여 나온 결과로 새로운 column 생성 가능
concat_df2.head()

A텔레콤    B전자    C은행   D철강   F화학  F화학_add_500
2023-01-02  48000  60000  54000  5000  3000         3500
2023-01-03  48500  61000  55000  5100  3100         3600
2023-01-04  49000  62000  56000  5200  3200         3700

In [48]:
# index 방향으로 date와 값들 추가

concat_df2.loc['2023-01-06', :] = [50000, 63000, 57000, 5300, 3300, 3800]
concat_df2

A텔레콤      B전자      C은행     D철강     F화학  F화학_add_500
2023-01-02  48000.0  60000.0  54000.0  5000.0  3000.0       3500.0
2023-01-03  48500.0  61000.0  55000.0  5100.0  3100.0       3600.0
2023-01-04  49000.0  62000.0  56000.0  5200.0  3200.0       3700.0
2023-01-06  50000.0  63000.0  57000.0  5300.0  3300.0       3800.0

In [49]:
concat_df2.loc['2023-01-05', :] = concat_df2.loc['2023-01-06', :] - 50
concat_df2

A텔레콤      B전자      C은행     D철강     F화학  F화학_add_500
2023-01-02  48000.0  60000.0  54000.0  5000.0  3000.0       3500.0
2023-01-03  48500.0  61000.0  55000.0  5100.0  3100.0       3600.0
2023-01-04  49000.0  62000.0  56000.0  5200.0  3200.0       3700.0
2023-01-06  50000.0  63000.0  57000.0  5300.0  3300.0       3800.0
2023-01-05  49950.0  62950.0  56950.0  5250.0  3250.0       3750.0

In [50]:
# sort (index)
concat_df2.sort_index()          # index를 기준으로 정렬

A텔레콤      B전자      C은행     D철강     F화학  F화학_add_500
2023-01-02  48000.0  60000.0  54000.0  5000.0  3000.0       3500.0
2023-01-03  48500.0  61000.0  55000.0  5100.0  3100.0       3600.0
2023-01-04  49000.0  62000.0  56000.0  5200.0  3200.0       3700.0
2023-01-05  49950.0  62950.0  56950.0  5250.0  3250.0       3750.0
2023-01-06  50000.0  63000.0  57000.0  5300.0  3300.0       3800.0

In [51]:
# sort (values)
concat_df2.sort_values(by='B전자')   # column기준으로 정렬

A텔레콤      B전자      C은행     D철강     F화학  F화학_add_500
2023-01-02  48000.0  60000.0  54000.0  5000.0  3000.0       3500.0
2023-01-03  48500.0  61000.0  55000.0  5100.0  3100.0       3600.0
2023-01-04  49000.0  62000.0  56000.0  5200.0  3200.0       3700.0
2023-01-05  49950.0  62950.0  56950.0  5250.0  3250.0       3750.0
2023-01-06  50000.0  63000.0  57000.0  5300.0  3300.0       3800.0

In [52]:
concat_df2.sort_values(by='B전자', ascending = False)  # 내림차순

A텔레콤      B전자      C은행     D철강     F화학  F화학_add_500
2023-01-06  50000.0  63000.0  57000.0  5300.0  3300.0       3800.0
2023-01-05  49950.0  62950.0  56950.0  5250.0  3250.0       3750.0
2023-01-04  49000.0  62000.0  56000.0  5200.0  3200.0       3700.0
2023-01-03  48500.0  61000.0  55000.0  5100.0  3100.0       3600.0
2023-01-02  48000.0  60000.0  54000.0  5000.0  3000.0       3500.0

## 데이터 삭제

In [53]:
concat_df2.drop('2023-01-04', inplace = True)   # 변수 선언 하지않더라도 inplace = True를 하면 바로 제거됨, axis = 0
concat_df2

A텔레콤      B전자      C은행     D철강     F화학  F화학_add_500
2023-01-02  48000.0  60000.0  54000.0  5000.0  3000.0       3500.0
2023-01-03  48500.0  61000.0  55000.0  5100.0  3100.0       3600.0
2023-01-06  50000.0  63000.0  57000.0  5300.0  3300.0       3800.0
2023-01-05  49950.0  62950.0  56950.0  5250.0  3250.0       3750.0

In [55]:
concat_df2.drop(['C은행', 'D철강'], axis = 1)     # column 방향을 지정해줘야 제거됨, 여러개를 제거할 경우 list로 만들어줘야 함

A텔레콤      B전자     F화학  F화학_add_500
2023-01-02  48000.0  60000.0  3000.0       3500.0
2023-01-03  48500.0  61000.0  3100.0       3600.0
2023-01-06  50000.0  63000.0  3300.0       3800.0
2023-01-05  49950.0  62950.0  3250.0       3750.0

### 데이터프레임 다루기

In [170]:
# column끼리 연산이 가능하다.
concat_df2['A텔레콤'] = concat_df2['A텔레콤'] + concat_df2['B전자']   
concat_df2.head()

A텔레콤      B전자      C은행     D철강     F화학  F화학_add_500
2023-01-02  108000.0  60000.0  54000.0  5000.0  3000.0       3500.0
2023-01-03  109500.0  61000.0  55000.0  5100.0  3100.0       3600.0
2023-01-06  113000.0  63000.0  57000.0  5300.0  3300.0       3800.0
2023-01-05  112900.0  62950.0  56950.0  5250.0  3250.0       3750.0

In [171]:
# 날짜 별 금액의 총합 구하고 'sum' column 추가
concat_df2['sum'] = concat_df2.sum(axis = 1)
concat_df2

A텔레콤      B전자      C은행     D철강     F화학  F화학_add_500       sum
2023-01-02  108000.0  60000.0  54000.0  5000.0  3000.0       3500.0  233500.0
2023-01-03  109500.0  61000.0  55000.0  5100.0  3100.0       3600.0  237300.0
2023-01-06  113000.0  63000.0  57000.0  5300.0  3300.0       3800.0  245400.0
2023-01-05  112900.0  62950.0  56950.0  5250.0  3250.0       3750.0  245050.0

In [172]:
concat_df2.min(axis = 0)

A텔레콤           108000.0
B전자             60000.0
C은행             54000.0
D철강              5000.0
F화학              3000.0
F화학_add_500      3500.0
sum            233500.0
dtype: float64

In [173]:
# 요약 통계량 
concat_df2.describe()

A텔레콤           B전자           C은행          D철강          F화학  \
count       4.000000      4.000000      4.000000     4.000000     4.000000   
mean   110850.000000  61737.500000  55737.500000  5162.500000  3162.500000   
std      2501.332978   1486.256483   1486.256483   137.689264   137.689264   
min    108000.000000  60000.000000  54000.000000  5000.000000  3000.000000   
25%    109125.000000  60750.000000  54750.000000  5075.000000  3075.000000   
50%    111200.000000  61975.000000  55975.000000  5175.000000  3175.000000   
75%    112925.000000  62962.500000  56962.500000  5262.500000  3262.500000   
max    113000.000000  63000.000000  57000.000000  5300.000000  3300.000000   

       F화학_add_500            sum  
count     4.000000       4.000000  
mean   3662.500000  240312.500000  
std     137.689264    5882.512927  
min    3500.000000  233500.000000  
25%    3575.000000  236350.000000  
50%    3675.000000  241175.000000  
75%    3762.500000  245137.500000  
max    3800.000000  245400.000000

### 결측치 처리

In [41]:
import numpy as np

concat_df2.loc['2023-01-03', 'C은행':'F화학'] = np.NaN  # 결측치 만들기

In [42]:
concat_df2

A텔레콤      B전자      C은행     D철강     F화학  F화학_add_500
2023-01-02  48000.0  60000.0  54000.0  5000.0  3000.0       3500.0
2023-01-03  48500.0  61000.0      NaN     NaN     NaN       3600.0
2023-01-06  50000.0  63000.0  57000.0  5300.0  3300.0       3800.0
2023-01-05  49950.0  62950.0  56950.0  5250.0  3250.0       3750.0

In [176]:
concat_df2.dropna(axis = 0)   # row방향

A텔레콤      B전자      C은행     D철강     F화학  F화학_add_500       sum
2023-01-02  108000.0  60000.0  54000.0  5000.0  3000.0       3500.0  233500.0
2023-01-06  113000.0  63000.0  57000.0  5300.0  3300.0       3800.0  245400.0
2023-01-05  112900.0  62950.0  56950.0  5250.0  3250.0       3750.0  245050.0

In [177]:
concat_df2.dropna(axis = 1)   # column방향

A텔레콤      B전자  F화학_add_500       sum
2023-01-02  108000.0  60000.0       3500.0  233500.0
2023-01-03  109500.0  61000.0       3600.0  237300.0
2023-01-06  113000.0  63000.0       3800.0  245400.0
2023-01-05  112900.0  62950.0       3750.0  245050.0

### 결측치 대체

In [59]:
concat_df2.loc[pd.to_datetime('2023-01-04')] = concat_df2.loc[pd.to_datetime('2023-01-02')] + 100
concat_df2 = concat_df2.sort_index()

TypeError: '<' not supported between instances of 'str' and 'Timestamp'

In [187]:
concat_df2.fillna(0)    # NaN값을 0으로 대체

A텔레콤      B전자      C은행     D철강     F화학  F화학_add_500  \
2023-01-02 00:00:00  108000.0  60000.0  54000.0  5000.0  3000.0       3500.0   
2023-01-03 00:00:00  109500.0  61000.0      0.0     0.0     0.0       3600.0   
2023-01-06 00:00:00  113000.0  63000.0  57000.0  5300.0  3300.0       3800.0   
2023-01-05 00:00:00  112900.0  62950.0  56950.0  5250.0  3250.0       3750.0   
2023-01-04           108100.0  60100.0  54100.0  5100.0  3100.0       3600.0   

                          sum  
2023-01-02 00:00:00  233500.0  
2023-01-03 00:00:00  237300.0  
2023-01-06 00:00:00  245400.0  
2023-01-05 00:00:00  245050.0  
2023-01-04           233600.0

In [188]:
concat_df2.fillna(method = 'ffill')  # 앞에 있는 값으로 대체

A텔레콤      B전자      C은행     D철강     F화학  F화학_add_500  \
2023-01-02 00:00:00  108000.0  60000.0  54000.0  5000.0  3000.0       3500.0   
2023-01-03 00:00:00  109500.0  61000.0  54000.0  5000.0  3000.0       3600.0   
2023-01-06 00:00:00  113000.0  63000.0  57000.0  5300.0  3300.0       3800.0   
2023-01-05 00:00:00  112900.0  62950.0  56950.0  5250.0  3250.0       3750.0   
2023-01-04           108100.0  60100.0  54100.0  5100.0  3100.0       3600.0   

                          sum  
2023-01-02 00:00:00  233500.0  
2023-01-03 00:00:00  237300.0  
2023-01-06 00:00:00  245400.0  
2023-01-05 00:00:00  245050.0  
2023-01-04           233600.0

In [189]:
concat_df2.fillna(method = 'bfill')  # 뒤에 있는 값으로 대체

A텔레콤      B전자      C은행     D철강     F화학  F화학_add_500  \
2023-01-02 00:00:00  108000.0  60000.0  54000.0  5000.0  3000.0       3500.0   
2023-01-03 00:00:00  109500.0  61000.0  57000.0  5300.0  3300.0       3600.0   
2023-01-06 00:00:00  113000.0  63000.0  57000.0  5300.0  3300.0       3800.0   
2023-01-05 00:00:00  112900.0  62950.0  56950.0  5250.0  3250.0       3750.0   
2023-01-04           108100.0  60100.0  54100.0  5100.0  3100.0       3600.0   

                          sum  
2023-01-02 00:00:00  233500.0  
2023-01-03 00:00:00  237300.0  
2023-01-06 00:00:00  245400.0  
2023-01-05 00:00:00  245050.0  
2023-01-04           233600.0

In [190]:
concat_df2.interpolate()

A텔레콤      B전자      C은행     D철강     F화학  F화학_add_500  \
2023-01-02 00:00:00  108000.0  60000.0  54000.0  5000.0  3000.0       3500.0   
2023-01-03 00:00:00  109500.0  61000.0  55500.0  5150.0  3150.0       3600.0   
2023-01-06 00:00:00  113000.0  63000.0  57000.0  5300.0  3300.0       3800.0   
2023-01-05 00:00:00  112900.0  62950.0  56950.0  5250.0  3250.0       3750.0   
2023-01-04           108100.0  60100.0  54100.0  5100.0  3100.0       3600.0   

                          sum  
2023-01-02 00:00:00  233500.0  
2023-01-03 00:00:00  237300.0  
2023-01-06 00:00:00  245400.0  
2023-01-05 00:00:00  245050.0  
2023-01-04           233600.0

### 중복제거

In [184]:
concat_df3 = concat_df2.copy()
concat4 = pd.concat([concat_df2, concat_df3])
concat4

A텔레콤      B전자      C은행     D철강     F화학  F화학_add_500  \
2023-01-02 00:00:00  108000.0  60000.0  54000.0  5000.0  3000.0       3500.0   
2023-01-03 00:00:00  109500.0  61000.0      NaN     NaN     NaN       3600.0   
2023-01-06 00:00:00  113000.0  63000.0  57000.0  5300.0  3300.0       3800.0   
2023-01-05 00:00:00  112900.0  62950.0  56950.0  5250.0  3250.0       3750.0   
2023-01-04           108100.0  60100.0  54100.0  5100.0  3100.0       3600.0   
2023-01-02 00:00:00  108000.0  60000.0  54000.0  5000.0  3000.0       3500.0   
2023-01-03 00:00:00  109500.0  61000.0      NaN     NaN     NaN       3600.0   
2023-01-06 00:00:00  113000.0  63000.0  57000.0  5300.0  3300.0       3800.0   
2023-01-05 00:00:00  112900.0  62950.0  56950.0  5250.0  3250.0       3750.0   
2023-01-04           108100.0  60100.0  54100.0  5100.0  3100.0       3600.0   

                          sum  
2023-01-02 00:00:00  233500.0  
2023-01-03 00:00:00  237300.0  
2023-01-06 00:00:00  245400.0  
2023-01-05 00:00:00  245050.0  
2023-01-04           233600.0  
2023-01-02 00:00:00  233500.0  
2023-01-03 00:00:00  237300.0  
2023-01-06 00:00:00  245400.0  
2023-01-05 00:00:00  245050.0  
2023-01-04           233600.0

In [185]:
concat4.drop_duplicates()   # 중복 제거

A텔레콤      B전자      C은행     D철강     F화학  F화학_add_500  \
2023-01-02 00:00:00  108000.0  60000.0  54000.0  5000.0  3000.0       3500.0   
2023-01-03 00:00:00  109500.0  61000.0      NaN     NaN     NaN       3600.0   
2023-01-06 00:00:00  113000.0  63000.0  57000.0  5300.0  3300.0       3800.0   
2023-01-05 00:00:00  112900.0  62950.0  56950.0  5250.0  3250.0       3750.0   
2023-01-04           108100.0  60100.0  54100.0  5100.0  3100.0       3600.0   

                          sum  
2023-01-02 00:00:00  233500.0  
2023-01-03 00:00:00  237300.0  
2023-01-06 00:00:00  245400.0  
2023-01-05 00:00:00  245050.0  
2023-01-04           233600.0

### 실습
- Q1. 2022-01-01 ~ 2022-12-01 월초 인덱스를 생성
- Q2. Q1에서 생성한 인덱스를 가지고 데이터 프레임 생성(값은 자율, 이때 칼럼이름은 value)
- Q3. value 컬럼에서 100을 더한 value_add_100 컬럼을 생성
- Q4. value 컬럼과 value_add_100 컬럼을 평균값이 들어간 mean 컬럼을 생성

In [193]:
# Q1
dates = pd.date_range('2022-01-01', '2022-12-01', freq = 'MS')
dates

DatetimeIndex(['2022-01-01', '2022-02-01', '2022-03-01', '2022-04-01',
               '2022-05-01', '2022-06-01', '2022-07-01', '2022-08-01',
               '2022-09-01', '2022-10-01', '2022-11-01', '2022-12-01'],
              dtype='datetime64[ns]', freq='MS')

In [211]:
# Q2
values = np.linspace(0, 100, 12)
df = pd.DataFrame(values, index = dates)
df.columns = ['value']                     # 컬럼명 변경 / df.rename(columns = {0:'value'}, inplace = True)
df

value
2022-01-01    0.000000
2022-02-01    9.090909
2022-03-01   18.181818
2022-04-01   27.272727
2022-05-01   36.363636
2022-06-01   45.454545
2022-07-01   54.545455
2022-08-01   63.636364
2022-09-01   72.727273
2022-10-01   81.818182
2022-11-01   90.909091
2022-12-01  100.000000

In [215]:
# Q3
df['value_add_100'] = df['value'] + 100
df

value  value_add_100
2022-01-01    0.000000     100.000000
2022-02-01    9.090909     109.090909
2022-03-01   18.181818     118.181818
2022-04-01   27.272727     127.272727
2022-05-01   36.363636     136.363636
2022-06-01   45.454545     145.454545
2022-07-01   54.545455     154.545455
2022-08-01   63.636364     163.636364
2022-09-01   72.727273     172.727273
2022-10-01   81.818182     181.818182
2022-11-01   90.909091     190.909091
2022-12-01  100.000000     200.000000

In [216]:
# Q4
df['mean'] = df.mean(axis = 1)           # column방향으로
df

value  value_add_100        mean
2022-01-01    0.000000     100.000000   50.000000
2022-02-01    9.090909     109.090909   59.090909
2022-03-01   18.181818     118.181818   68.181818
2022-04-01   27.272727     127.272727   77.272727
2022-05-01   36.363636     136.363636   86.363636
2022-06-01   45.454545     145.454545   95.454545
2022-07-01   54.545455     154.545455  104.545455
2022-08-01   63.636364     163.636364  113.636364
2022-09-01   72.727273     172.727273  122.727273
2022-10-01   81.818182     181.818182  131.818182
2022-11-01   90.909091     190.909091  140.909091
2022-12-01  100.000000     200.000000  150.000000